// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92F7SQRxMshTXTJuqchJUkm3KQY2ref8',
    appId: '1:947436166057:android:81c6517824b0fee78302b8',
    messagingSenderId: '947436166057',
    projectId: 'flutter-chat-app-74ad7',
    storageBucket: 'flutter-chat-app-74ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqE1pWRvBkIFaa3C9r22r8vIgQ7TEduBU',
    appId: '1:947436166057:ios:70c9aa1cd69953da8302b8',
    messagingSenderId: '947436166057',
    projectId: 'flutter-chat-app-74ad7',
    storageBucket: 'flutter-chat-app-74ad7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9lN5-9ZvBenNminsxgRyyqQ_omYjsC2o',
    appId: '1:947436166057:web:10d704c02412f2bf8302b8',
    messagingSenderId: '947436166057',
    projectId: 'flutter-chat-app-74ad7',
    authDomain: 'flutter-chat-app-74ad7.firebaseapp.com',
    storageBucket: 'flutter-chat-app-74ad7.appspot.com',
  );

}